require "json"
require "file_utils"

module ACD
  module Kemal
    class App
      private def mount_workflows_create_endpoints
        post "/v1/workflows/create" do |env|
          env.response.content_type = "application/json"

          body = env.request.body.try(&.gets_to_end)
          unless body
            next json_error(env, 400, "bad_request", "request body is required")
          end

          params = JSON.parse body
          name = params["name"]?.try(&.as_s?) || params["id"]?.try(&.as_s?) || params["workflow_id"]?.try(&.as_s?)
          unless name && !name.empty?
            next json_error(env, 400, "bad_request", "workflow name is required")
          end

          nodes = params["nodes"]?.try(&.as_a?) || [] of JSON::Any
          schedule = params["schedule"]?.try(&.as_s?)
          tag = params["tag"]?.try(&.as_s?)
          trigger_message = params["trigger_message"]?.try(&.as_s?) || params["trigger"]?.try(&.as_s?)
          is_service = !schedule.nil? && !schedule.empty?

          workflows_root = ENV["OCAWE_WORKFLOWS_ROOT"]? || File.join(Dir.current, "src", "workflows")
          workflow_dir = File.join(workflows_root, name)
          cawfile_path = File.join(workflow_dir, "Cawfile")
          agents_dir = File.join(workflow_dir, "agents")
          skills_dir = File.join(workflow_dir, "skills")

          Dir.mkdir_p workflow_dir
          Dir.mkdir_p agents_dir
          Dir.mkdir_p skills_dir

          lines = [] of String
          lines << "# Auto-generated by octra-copy"
          lines << "# Trigger config: schedule=#{schedule}, tag=#{tag}"
          lines << ""

          if is_service
            lines << "@[Service]"
          end

          lines << "workflow \"#{name}\" do"

          if trigger_message && !trigger_message.empty?
            lines << "  agent \"trigger\", prompt: #{trigger_message.inspect}"
          end

          nodes.each do |node|
            kind = node["kind"]?.try(&.as_s?) || "agent"
            node_id = node["id"]?.try(&.as_s?) || "node-#{rand(10000)}"

            case kind
            when "agent"
              prompt = node["prompt"]?.try(&.as_s?) || "You are a helpful assistant"
              model = node["model"]?.try(&.as_s?)
              if model
                lines << "  agent #{node_id.inspect}, prompt: #{prompt.inspect}, model: #{model.inspect}"
              else
                lines << "  agent #{node_id.inspect}, prompt: #{prompt.inspect}"
              end
            when "exec"
              ref = node["ref"]?.try(&.as_s?) || "script.sh"
              runtime = node["runtime"]?.try(&.as_s?)
              if runtime
                lines << "  exec #{node_id.inspect}, ref: #{ref.inspect}, runtime: #{runtime.inspect}"
              else
                lines << "  exec #{node_id.inspect}, ref: #{ref.inspect}"
              end
            when "api"
              url = node["url"]?.try(&.as_s?) || "http://localhost"
              method = node["method"]?.try(&.as_s?) || "GET"
              case method.upcase
              when "GET"
                lines << "  get #{url.inspect}, id: #{node_id.inspect}"
              when "POST"
                lines << "  post #{url.inspect}, id: #{node_id.inspect}"
              when "PUT"
                lines << "  put #{url.inspect}, id: #{node_id.inspect}"
              else
                lines << "  api #{method.inspect}, #{url.inspect}, id: #{node_id.inspect}"
              end
            when "voice"
              config = node["config"]?.try(&.as_s?) || "{}"
              lines << "  voice #{node_id.inspect}, config: #{config.inspect}"
            when "rag"
              config = node["config"]?.try(&.as_s?) || "{}"
              lines << "  rag #{node_id.inspect}, config: #{config.inspect}"
            when "suspend"
              reason = node["reason"]?.try(&.as_s?) || "Waiting for input"
              lines << "  suspend #{node_id.inspect}, reason: #{reason.inspect}"
            end
          end

          lines << "end\n"

          File.write cawfile_path, lines.join("\n")

          {
            workflow_id: name,
            path:         cawfile_path,
          }.to_json
        end

        get "/v1/nodes" do |env|
          env.response.content_type = "application/json"
          [
            {kind: "agent",   label: "Agent",   fields: [{key: "prompt", type: "text", required: false}, {key: "model", type: "text", required: false}]},
            {kind: "exec",    label: "Exec",    fields: [{key: "ref", type: "text", required: true}, {key: "runtime", type: "text", required: false}]},
            {kind: "api",     label: "API",     fields: [{key: "url", type: "text", required: true}, {key: "method", type: "select", options: ["GET", "POST", "PUT"], required: false}]},
            {kind: "voice",   label: "Voice",   fields: [{key: "config", type: "text", required: false}]},
            {kind: "rag",     label: "RAG",     fields: [{key: "config", type: "text", required: false}]},
            {kind: "suspend", label: "Suspend", fields: [{key: "reason", type: "text", required: false}]},
            {kind: "skill",   label: "Skill",   fields: [{key: "skill", type: "text", required: true}]},
          ].to_json
        end
      end
    end
  end
end
