require "file_utils"

require "../config/app_config"
require "../../discovery/workflow_locator"
require "../../agents/loader"
require "../../skills/loader"

module CogniCore
  module Compiler
    class Compiler
      def compile_all
        config = Config.load
        locator = ACD::Discovery::WorkflowLocator.new(config.preferred_workflows_root, config.fallback_workflows_root)
        agent_loader = ACD::Agents::Loader.new
        skill_loader = ACD::Skills::Loader.new

        bundles = locator.list_workflows

        entries = bundles.map do |bundle|
          agents = agent_loader.load_dir(bundle.agents_dir)
          skills = skill_loader.load_dir(bundle.skills_dir)
          workflow_content = File.read(bundle.workflow_file)
          node_counts = extract_node_counts(workflow_content)
          validate_tool_nodes(bundle.root_path, workflow_content)
          {
            id: bundle.id,
            source_root_type: bundle.source_root_type,
            root_path: bundle.root_path,
            workflow_file: bundle.workflow_file,
            agents_dir: bundle.agents_dir,
            skills_dir: bundle.skills_dir,
            agent_count: agents.size,
            skill_count: skills.size,
            agent_node_count: node_counts[:agent_node_count],
            skill_node_count: node_counts[:skill_node_count],
            tool_count: node_counts[:tool_count],
            custom_count: node_counts[:custom_count],
            approve_count: node_counts[:approve_count],
          }
        end

        write_registry(entries, config.output)
        puts "[compiler] compiled #{entries.size} workflow bundles -> #{config.output}"
      end

      private def write_registry(entries, output_path : String)
        FileUtils.mkdir_p(File.dirname(output_path))
        content = String.build do |io|
          io.puts "# This file is generated by src/tools/compile_dsl.cr"
          io.puts "module CogniCore"
          io.puts "  module Registry"
          io.puts "    WORKFLOW_BUNDLES = ["

          entries.each do |entry|
            io.puts "      {id: \"#{entry[:id]}\", source_root_type: \"#{entry[:source_root_type]}\", root_path: \"#{entry[:root_path]}\", workflow_file: \"#{entry[:workflow_file]}\", agents_dir: \"#{entry[:agents_dir]}\", skills_dir: \"#{entry[:skills_dir]}\", agent_count: #{entry[:agent_count]}, skill_count: #{entry[:skill_count]}, agent_node_count: #{entry[:agent_node_count]}, skill_node_count: #{entry[:skill_node_count]}, tool_count: #{entry[:tool_count]}, custom_count: #{entry[:custom_count]}, approve_count: #{entry[:approve_count]}},"
          end

          io.puts "    ] of NamedTuple(id: String, source_root_type: String, root_path: String, workflow_file: String, agents_dir: String, skills_dir: String, agent_count: Int32, skill_count: Int32, agent_node_count: Int32, skill_node_count: Int32, tool_count: Int32, custom_count: Int32, approve_count: Int32)"
          io.puts "  end"
          io.puts "end"
        end
        File.write(output_path, content)
      end

      private def extract_node_counts(content : String)
        {
          agent_node_count: content.scan(/^\s*agent\s+"/m).size.to_i32,
          skill_node_count: content.scan(/^\s*skill\s+"/m).size.to_i32,
          tool_count: content.scan(/^\s*tool\s+"/m).size.to_i32,
          custom_count: content.scan(/^\s*custom\s+"/m).size.to_i32,
          approve_count: content.scan(/^\s*approve\s+"/m).size.to_i32,
        }
      end

      private def validate_tool_nodes(bundle_root : String, content : String)
        scripts = [] of String

        content.scan(/^\s*tool\s+"[^"]+"\s*,.*script:\s*{[^}]*path:\s*"([^"]+)"/m) do |match|
          scripts << match[1]
        end
        content.scan(/^\s*tool\s+"[^"]+"\s*,.*script:\s*"([^"]+)"/m) do |match|
          scripts << match[1]
        end

        scripts.uniq!
        scripts.each do |script|
          raise "tool script must be relative: #{script}" if script.starts_with?("/")
          raise "tool script must be under tools/: #{script}" unless script.starts_with?("tools/")

          resolved = File.expand_path(script, bundle_root)
          tools_root = File.expand_path("tools", bundle_root)
          unless resolved.starts_with?(tools_root + "/") || resolved == tools_root
            raise "tool script escapes tools root: #{script}"
          end
          raise "tool script not found: #{resolved}" unless File.exists?(resolved)
        end
      end

      struct Config
        getter preferred_workflows_root : String
        getter fallback_workflows_root : String
        getter output : String

        def initialize(
          @preferred_workflows_root : String = "./src/workflows",
          @fallback_workflows_root : String = "./src/workflows",
          @output : String = "generated/registry.cr"
        )
        end

        def self.load
          app_config = CogniCore::Config::AppConfig.settings
          Config.new(
            preferred_workflows_root: app_config.workflows.preferred_workflows_root,
            fallback_workflows_root: app_config.workflows.fallback_workflows_root,
            output: app_config.compiler.output,
          )
        end
      end
    end
  end
end
